=== yanoharuto/MachRider/DriveAction/data/Json/Schema/stageDataSchema.json
{
  "$schema": "https://json-schema.org/draft/2019-09/schema",
  "$id": "http://example.com/example.json",
  "type": "object",
  "default": {},
  "title": "Root Schema",
  "required": [
    "width",
    "length",
    "enemyFilePath",
    "collectFilePath",
    "playerPositionFilePath",
    "gameTime",
    "stageScoreFilePath"
  ],
  "properties": {
    "width": {
      "type": "integer",
      "default": 0,
      "title": "The width Schema",
      "examples": [
        6000
      ]
    },
    "length": {
      "type": "integer",
      "default": 0,
      "title": "The length Schema",
      "examples": [
        6000
      ]
    },
    "enemyFilePath": {
      "type": "string",
      "default": "",
      "title": "The enemyFilePath Schema",
      "examples": [
        "data/Json/StageData/Stage1/enemyData.json"
      ]
    },
    "collectFilePath": {
      "type": "string",
      "default": "",
      "title": "The collectFilePath Schema",
      "examples": [
        "data/Json/StageData/Stage1/collectData.json"
      ]
    },
    "playerPositionFilePath": {
      "type": "string",
      "default": "",
      "title": "The playerPositionFilePath Schema",
      "examples": [
        "data/Json/StageData/Stage1/playerData.json"
      ]
    },
    "gameTime": {
      "type": "integer",
      "default": 0,
      "title": "The gameTime Schema",
      "examples": [
        75
      ]
    },
    "stageScoreFilePath": {
      "type": "string",
      "default": "",
      "title": "The stageScoreFilePath Schema",
      "examples": [
        "data/Json/StageData/Stage1/scoreData.json"
      ]
    }
  },
  "examples": [
    {
      "width": 6000,
      "length": 6000,
      "enemyFilePath": "data/Json/StageData/Stage1/enemyData.json",
      "collectFilePath": "data/Json/StageData/Stage1/collectData.json",
      "playerPositionFilePath": "data/Json/StageData/Stage1/playerData.json",
      "gameTime": 75,
      "stageScoreFilePath": "data/Json/StageData/Stage1/scoreData.json"
    }
  ]
}

=== yanoharuto/MachRider/DriveAction/data/Json/StageData/Stage3/stageData.json
{
  "width": 6000,
  "length": 6000,
  "enemyFilePath": "data/Json/StageData/Stage3/enemyData.json",
  "collectFilePath": "data/Json/StageData/Stage3/collectData.json",
  "playerPositionFilePath": "data/Json/StageData/Stage3/playerData.json",
  "gameTime": 75,
  "stageScoreFilePath": "data/Json/StageData/Stage3/scoreData.json"
}
